
version: 2

models:
    - name: bronze_testmodel
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null


